import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
  BorderStyle,
  TableRow,
  TableCell,
  Table,
  WidthType,
  ShadingType,
} from 'docx';
import { saveAs } from 'file-saver';
import type { MarketingPlanData } from '@/hooks/useMarketingPlan';

interface SectionDef {
  title: string;
  key: keyof MarketingPlanData;
  number: number;
}

const SECTIONS: SectionDef[] = [
  { title: 'Mercato Target', key: 'target_market', number: 1 },
  { title: 'Strategia di Acquisizione', key: 'acquisition_strategy', number: 2 },
  { title: 'Piano Prezzi', key: 'pricing_strategy', number: 3 },
  { title: 'Posizionamento Competitivo', key: 'competitive_positioning', number: 4 },
  { title: 'Canali di Comunicazione', key: 'communication_channels', number: 5 },
  { title: 'Budget Marketing', key: 'budget_allocation', number: 6 },
];

function contentToParagraphs(text: string): Paragraph[] {
  if (!text || !text.trim()) {
    return [new Paragraph({ children: [new TextRun({ text: 'Da completare', italics: true, color: '999999' })] })];
  }

  const lines = text.split('\n');
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 100 } }));
      continue;
    }

    if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !trimmed.startsWith('•') && !trimmed.startsWith('-')) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: trimmed, bold: true, size: 24, color: '16A34A' })],
        spacing: { before: 200, after: 100 },
      }));
      continue;
    }

    if (trimmed.startsWith('•') || trimmed.startsWith('-')) {
      const bulletText = trimmed.replace(/^[•\-]\s*/, '');
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: bulletText, size: 22 })],
        bullet: { level: 0 },
        spacing: { after: 40 },
      }));
      continue;
    }

    if (line.startsWith('  ') && (trimmed.startsWith('-') || trimmed.startsWith('•'))) {
      const bulletText = trimmed.replace(/^[•\-]\s*/, '');
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: bulletText, size: 22 })],
        bullet: { level: 1 },
        spacing: { after: 40 },
      }));
      continue;
    }

    paragraphs.push(new Paragraph({
      children: [new TextRun({ text: trimmed, size: 22 })],
      spacing: { after: 80 },
    }));
  }

  return paragraphs;
}

function createSummaryTable(autoGeneratedData: any): Table {
  const data = [
    ['Avanzamento Marketing', `${autoGeneratedData.marketingCompletionRate}%`],
    ['Budget Stimato Min', `€${autoGeneratedData.marketingCostsMin.toLocaleString('it-IT')}`],
    ['Budget Stimato Max', `€${autoGeneratedData.marketingCostsMax.toLocaleString('it-IT')}`],
    ['Timeline Marketing', `${autoGeneratedData.marketingDays} giorni`],
    ['Step Marketing', `${autoGeneratedData.marketingSteps}`],
  ];

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Indicatore', bold: true, color: 'FFFFFF', size: 22 })], alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.SOLID, color: '16A34A' },
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Valore', bold: true, color: 'FFFFFF', size: 22 })], alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.SOLID, color: '16A34A' },
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
        ],
      }),
      ...data.map(([label, value], idx) =>
        new TableRow({
          children: [
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: label, size: 22 })] })],
              shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F0FDF4' } : undefined,
            }),
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 22 })], alignment: AlignmentType.RIGHT })],
              shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F0FDF4' } : undefined,
            }),
          ],
        })
      ),
    ],
  });
}

export async function exportMarketingPlanToDocx(
  marketingPlan: MarketingPlanData,
  autoGeneratedData: any,
  generatedContent?: Record<string, string> | null
): Promise<void> {
  const getContent = (key: string): string => {
    const saved = marketingPlan[key as keyof MarketingPlanData];
    if (saved && typeof saved === 'string' && saved.trim()) return saved;
    if (generatedContent?.[key]) return generatedContent[key];
    return '';
  };

  const children: any[] = [];

  // Cover page
  children.push(
    new Paragraph({ spacing: { before: 3000 } }),
    new Paragraph({
      children: [new TextRun({ text: 'PIANO MARKETING', bold: true, size: 56, color: '16A34A' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Strategia Commerciale Integrata', size: 32, color: '6B7280' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Generato il ${new Date().toLocaleDateString('it-IT', { day: 'numeric', month: 'long', year: 'numeric' })}`,
        size: 24,
        color: '9CA3AF',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // Table of contents
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'INDICE', bold: true, size: 36, color: '16A34A' })],
      spacing: { after: 400 },
    })
  );
  SECTIONS.forEach(s => {
    children.push(new Paragraph({
      children: [new TextRun({ text: `${s.number}. ${s.title}`, size: 24 })],
      spacing: { after: 100 },
    }));
  });
  children.push(new Paragraph({
    children: [new TextRun({ text: `${SECTIONS.length + 1}. Riepilogo KPI Marketing`, size: 24 })],
    spacing: { after: 100 },
  }));
  children.push(new Paragraph({ children: [new PageBreak()] }));

  // Content sections
  SECTIONS.forEach(section => {
    children.push(
      new Paragraph({
        text: `${section.number}. ${section.title}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 200 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '16A34A' } },
      }),
      ...contentToParagraphs(getContent(section.key as string)),
      new Paragraph({ children: [new PageBreak()] })
    );
  });

  // KPI summary page
  if (autoGeneratedData) {
    children.push(
      new Paragraph({
        text: `${SECTIONS.length + 1}. Riepilogo KPI Marketing`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 300 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '16A34A' } },
      }),
      createSummaryTable(autoGeneratedData)
    );

    if (autoGeneratedData.recommendedChannels) {
      children.push(
        new Paragraph({ spacing: { before: 400 } }),
        new Paragraph({
          children: [new TextRun({ text: 'Canali Raccomandati', bold: true, size: 28, color: '16A34A' })],
          spacing: { after: 200 },
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              children: ['Canale', 'Priorità', 'Budget Suggerito'].map(h =>
                new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: 'FFFFFF', size: 20 })], alignment: AlignmentType.CENTER })],
                  shading: { type: ShadingType.SOLID, color: '16A34A' },
                })
              ),
            }),
            ...autoGeneratedData.recommendedChannels.map((ch: any, idx: number) =>
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: ch.name, size: 20 })] })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F0FDF4' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: ch.priority, size: 20 })], alignment: AlignmentType.CENTER })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F0FDF4' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: ch.budget, size: 20 })], alignment: AlignmentType.CENTER })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F0FDF4' } : undefined }),
                ],
              })
            ),
          ],
        })
      );
    }
  }

  const doc = new Document({
    sections: [{ children }],
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
      },
    },
  });

  const blob = await Packer.toBlob(doc);
  const fileName = `piano-marketing-${new Date().toISOString().split('T')[0]}.docx`;
  saveAs(blob, fileName);
}
