import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
  BorderStyle,
  TableRow,
  TableCell,
  Table,
  WidthType,
  ShadingType,
} from 'docx';
import { saveAs } from 'file-saver';
import type { BusinessPlanData } from '@/hooks/useBusinessPlan';
import type { BusinessPlanIssue } from '@/lib/businessPlanValidator';
import { createVerificationReportDocx } from '@/lib/exportVerificationReport';

interface SectionDef {
  title: string;
  key: keyof BusinessPlanData;
  number: number;
}

const SECTIONS: SectionDef[] = [
  { title: 'Executive Summary', key: 'executive_summary', number: 1 },
  { title: 'Descrizione Società', key: 'company_description', number: 2 },
  { title: 'Analisi di Mercato', key: 'market_analysis', number: 3 },
  { title: 'Organizzazione', key: 'organization', number: 4 },
  { title: 'Prodotti e Servizi', key: 'products_services', number: 5 },
  { title: 'Strategia di Marketing', key: 'marketing_strategy', number: 6 },
  { title: 'Piano Finanziario', key: 'financial_plan', number: 7 },
];

function contentToParagraphs(text: string): Paragraph[] {
  if (!text || !text.trim()) {
    return [new Paragraph({ children: [new TextRun({ text: 'Da completare', italics: true, color: '999999' })] })];
  }

  const lines = text.split('\n');
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 100 } }));
      continue;
    }

    // All-caps lines as sub-headings
    if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !trimmed.startsWith('•') && !trimmed.startsWith('-')) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: trimmed, bold: true, size: 24, color: '2563EB' })],
        spacing: { before: 200, after: 100 },
      }));
      continue;
    }

    // Bullet points
    if (trimmed.startsWith('•') || trimmed.startsWith('-')) {
      const bulletText = trimmed.replace(/^[•\-]\s*/, '');
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: bulletText, size: 22 })],
        bullet: { level: 0 },
        spacing: { after: 40 },
      }));
      continue;
    }

    // Sub-bullets (indented)
    if (line.startsWith('  ') && (trimmed.startsWith('-') || trimmed.startsWith('•'))) {
      const bulletText = trimmed.replace(/^[•\-]\s*/, '');
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: bulletText, size: 22 })],
        bullet: { level: 1 },
        spacing: { after: 40 },
      }));
      continue;
    }

    // Regular paragraph
    paragraphs.push(new Paragraph({
      children: [new TextRun({ text: trimmed, size: 22 })],
      spacing: { after: 80 },
    }));
  }

  return paragraphs;
}

function createSummaryTable(autoGeneratedData: any): Table {
  const data = [
    ['Completamento', `${autoGeneratedData.completionRate}%`],
    ['Investimento Min', `€${autoGeneratedData.totalCostsMin.toLocaleString('it-IT')}`],
    ['Investimento Max', `€${autoGeneratedData.totalCostsMax.toLocaleString('it-IT')}`],
    ['Timeline', `${autoGeneratedData.totalDays} giorni`],
    ['Step Completati', `${autoGeneratedData.completedSteps}/${autoGeneratedData.totalSteps}`],
  ];

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Indicatore', bold: true, color: 'FFFFFF', size: 22 })], alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.SOLID, color: '2563EB' },
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Valore', bold: true, color: 'FFFFFF', size: 22 })], alignment: AlignmentType.CENTER })],
            shading: { type: ShadingType.SOLID, color: '2563EB' },
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
        ],
      }),
      ...data.map(([label, value], idx) =>
        new TableRow({
          children: [
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: label, size: 22 })] })],
              shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined,
            }),
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 22 })], alignment: AlignmentType.RIGHT })],
              shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined,
            }),
          ],
        })
      ),
    ],
  });
}

export async function exportBusinessPlanToDocx(
  businessPlan: BusinessPlanData,
  autoGeneratedData: any,
  generatedContent?: Record<string, string> | null,
  verificationIssues?: BusinessPlanIssue[]
): Promise<void> {
  const getContent = (key: string): string => {
    const saved = businessPlan[key as keyof BusinessPlanData];
    if (saved && typeof saved === 'string' && saved.trim()) return saved;
    if (generatedContent?.[key]) return generatedContent[key];
    return '';
  };

  const children: any[] = [];

  // Cover page
  children.push(
    new Paragraph({ spacing: { before: 3000 } }),
    new Paragraph({
      children: [new TextRun({ text: 'BUSINESS PLAN', bold: true, size: 56, color: '2563EB' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Società di Vendita Energia', size: 32, color: '6B7280' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Generato il ${new Date().toLocaleDateString('it-IT', { day: 'numeric', month: 'long', year: 'numeric' })}`,
        size: 24,
        color: '9CA3AF',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // Table of contents
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'INDICE', bold: true, size: 36, color: '2563EB' })],
      spacing: { after: 400 },
    })
  );
  SECTIONS.forEach(s => {
    children.push(new Paragraph({
      children: [new TextRun({ text: `${s.number}. ${s.title}`, size: 24 })],
      spacing: { after: 100 },
    }));
  });
  children.push(new Paragraph({
    children: [new TextRun({ text: `${SECTIONS.length + 1}. Dati e Analisi Finanziaria`, size: 24 })],
    spacing: { after: 100 },
  }));
  children.push(new Paragraph({ children: [new PageBreak()] }));

  // Content sections
  SECTIONS.forEach(section => {
    children.push(
      new Paragraph({
        text: `${section.number}. ${section.title}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 200 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '2563EB' } },
      }),
      ...contentToParagraphs(getContent(section.key as string)),
      new Paragraph({ children: [new PageBreak()] })
    );
  });

  // Financial data page
  if (autoGeneratedData) {
    children.push(
      new Paragraph({
        text: `${SECTIONS.length + 1}. Dati e Analisi Finanziaria`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 300 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '2563EB' } },
      }),
      createSummaryTable(autoGeneratedData)
    );

    if (autoGeneratedData.phaseData) {
      children.push(
        new Paragraph({ spacing: { before: 400 } }),
        new Paragraph({
          children: [new TextRun({ text: 'Dettaglio Fasi', bold: true, size: 28, color: '2563EB' })],
          spacing: { after: 200 },
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              children: ['Fase', 'Completamento', 'Costi', 'Durata', 'Step'].map(h =>
                new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: 'FFFFFF', size: 20 })], alignment: AlignmentType.CENTER })],
                  shading: { type: ShadingType.SOLID, color: '2563EB' },
                })
              ),
            }),
            ...autoGeneratedData.phaseData.map((phase: any, idx: number) =>
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: phase.name, size: 20 })] })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${phase.completion}%`, size: 20 })], alignment: AlignmentType.CENTER })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `€${Math.round(phase.costs).toLocaleString('it-IT')}`, size: 20 })], alignment: AlignmentType.RIGHT })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${phase.days} gg`, size: 20 })], alignment: AlignmentType.CENTER })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${phase.completed}/${phase.total}`, size: 20 })], alignment: AlignmentType.CENTER })], shading: idx % 2 === 0 ? { type: ShadingType.SOLID, color: 'F3F4F6' } : undefined }),
                ],
              })
            ),
          ],
        })
      );
    }
  }

  // Verification report
  if (verificationIssues && verificationIssues.length > 0) {
    children.push(...createVerificationReportDocx(verificationIssues, '2563EB'));
  }

  const doc = new Document({
    sections: [{ children }],
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
      },
    },
  });

  const blob = await Packer.toBlob(doc);
  const fileName = `business-plan-${new Date().toISOString().split('T')[0]}.docx`;
  saveAs(blob, fileName);
}
