import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { processSteps, phases } from '@/data/processSteps';
import { stepCostsData } from '@/types/stepCosts';
import type { StepProgress } from './useStepProgress';
import { generateAllSections, type ProjectContext } from '@/lib/generateBusinessPlanContent';

// BusinessPlanSection and BusinessPlanData interfaces
export interface BusinessPlanSection {
  id: string;
  title: string;
  content: string;
  order: number;
}

export interface BusinessPlanData {
  id?: string;
  project_id?: string;
  executive_summary: string;
  company_description: string;
  market_analysis: string;
  organization: string;
  products_services: string;
  marketing_strategy: string;
  financial_plan: string;
  updated_at?: string;
}

export const useBusinessPlan = (userId: string | undefined, projectId: string | undefined, stepProgress: Record<string, StepProgress>) => {
  const [businessPlan, setBusinessPlan] = useState<BusinessPlanData>({
    executive_summary: '',
    company_description: '',
    market_analysis: '',
    organization: '',
    products_services: '',
    marketing_strategy: '',
    financial_plan: '',
  });
  const [loading, setLoading] = useState(true);
  const [autoGeneratedData, setAutoGeneratedData] = useState<any>(null);
  const [generatedContent, setGeneratedContent] = useState<Record<string, string> | null>(null);
  const [projectContext, setProjectContext] = useState<ProjectContext | null>(null);

  // Generate data from existing process
  useEffect(() => {
    if (!stepProgress) return;

    const totalSteps = processSteps.length;
    const completedSteps = Object.values(stepProgress).filter(p => p.completed).length;
    const completionRate = totalSteps > 0 ? Math.round((completedSteps / totalSteps) * 100) : 0;

    let totalCostsMin = 0;
    let totalCostsMax = 0;
    processSteps.forEach(step => {
      if (step.costs) {
        totalCostsMin += step.costs.min;
        totalCostsMax += step.costs.max;
      }
    });

    const totalDays = processSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
    const completedDays = processSteps
      .filter(step => stepProgress[step.id]?.completed)
      .reduce((sum, step) => sum + step.estimatedDays, 0);

    const phaseData = phases.map(phase => {
      const phaseSteps = processSteps.filter(s => s.phase === phase.id);
      const completed = phaseSteps.filter(s => stepProgress[s.id]?.completed).length;
      const phaseCosts = phaseSteps.reduce((sum, step) => {
        if (step.costs) return sum + ((step.costs.min + step.costs.max) / 2);
        return sum;
      }, 0);
      const phaseDays = phaseSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
      
      return {
        name: phase.name,
        completion: Math.round((completed / phaseSteps.length) * 100),
        costs: phaseCosts,
        days: phaseDays,
        total: phaseSteps.length,
        completed
      };
    });

    setAutoGeneratedData({
      completionRate,
      totalCostsMin,
      totalCostsMax,
      totalDays,
      completedDays,
      completedSteps,
      totalSteps,
      phaseData
    });
  }, [stepProgress]);

  // Load business plan from database
  useEffect(() => {
    if (!userId || !projectId) {
      setLoading(false);
      return;
    }

    const loadBusinessPlan = async () => {
      try {
        const { data, error } = await supabase
          .from('business_plans')
          .select('*')
          .eq('project_id', projectId)
          .maybeSingle();

        if (error && error.code !== 'PGRST116') {
          console.error('Error loading business plan:', error);
        }

        if (data) {
          setBusinessPlan(data);
        }
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setLoading(false);
      }
    };

    loadBusinessPlan();
  }, [userId, projectId]);

  // Generate content and store project context for validation
  const generateContent = useCallback(async () => {
    if (!projectId || !stepProgress) return null;

    try {
      const [projectRes, simRes, channelsRes, costsRes, stepCostsRes] = await Promise.all([
        supabase.from('projects').select('*').eq('id', projectId).maybeSingle(),
        supabase.from('project_revenue_simulations').select('*').eq('project_id', projectId).maybeSingle(),
        supabase.from('project_sales_channels').select('*').eq('project_id', projectId),
        supabase.from('project_costs').select('*').eq('project_id', projectId),
        supabase.from('project_step_costs').select('*').eq('project_id', projectId),
      ]);

      const project = projectRes.data;
      const sim = simRes.data;
      const channels = channelsRes.data || [];
      const costs = costsRes.data || [];
      const dbStepCosts = (stepCostsRes.data || []) as { step_id: string; cost_item_id: string; amount: number }[];

      const phaseData = phases.map(phase => {
        const phaseSteps = processSteps.filter(s => s.phase === phase.id);
        const completed = phaseSteps.filter(s => stepProgress[s.id]?.completed).length;
        // Use real DB costs for phase costs
        const phaseCosts = phaseSteps.reduce((sum, step) => {
          const stepData = stepCostsData[step.id];
          if (!stepData) return sum;
          return sum + stepData.items.reduce((itemSum, item) => {
            const custom = dbStepCosts.find(sc => sc.step_id === step.id && sc.cost_item_id === item.id);
            return itemSum + (custom ? custom.amount : item.defaultAmount);
          }, 0);
        }, 0);
        const phaseDays = phaseSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
        return { name: phase.name, completion: Math.round((completed / phaseSteps.length) * 100), costs: phaseCosts, days: phaseDays, total: phaseSteps.length, completed };
      });

      // Calculate total investment from real DB step costs (custom overrides or defaults)
      let totalInvestmentCosts = 0;
      Object.keys(stepCostsData).forEach(stepId => {
        const stepData = stepCostsData[stepId];
        stepData.items.forEach(item => {
          const custom = dbStepCosts.find(sc => sc.step_id === stepId && sc.cost_item_id === item.id);
          totalInvestmentCosts += custom ? custom.amount : item.defaultAmount;
        });
      });

      let operationalCosts = 0;
      let passthroughCosts = 0;
      costs.forEach((c: any) => {
        const total = (c.amount || 0) * (c.quantity || 1);
        if (c.is_passthrough) passthroughCosts += total;
        else operationalCosts += total;
      });

      const ctx: ProjectContext = {
        projectName: project?.name || 'Progetto Reseller',
        projectDescription: project?.description || null,
        commodityType: project?.commodity_type || null,
        marketType: project?.market_type || null,
        regions: project?.regions || null,
        expectedVolumes: project?.expected_volumes || null,
        wholesalerName: project?.wholesaler_name || null,
        plannedStartDate: project?.planned_start_date || null,
        goLiveDate: project?.go_live_date || null,
        stepProgress,
        simulation: sim ? {
          monthlyContracts: (sim.monthly_contracts as number[]) || [30,40,50,60,70,80,90,100,100,100,100,100],
          spreadPerKwh: sim.spread_per_kwh ?? 0.015,
          spreadGasPerSmc: sim.spread_gas_per_smc ?? 0.03,
          ccvMonthly: sim.ccv_monthly ?? 8.5,
          ccvGasMonthly: sim.ccv_gas_monthly ?? 6.5,
          avgMonthlyConsumption: sim.avg_monthly_consumption ?? 200,
          avgMonthlyConsumptionGas: sim.avg_monthly_consumption_gas ?? 80,
          activationRate: sim.activation_rate ?? 85,
          monthlyChurnRate: sim.monthly_churn_rate ?? 1.5,
          clientType: sim.client_type ?? 'domestico',
          commodityType: sim.commodity_type ?? 'luce',
        } : null,
        salesChannels: channels.map((ch: any) => ({
          channel_name: ch.channel_name,
          commission_amount: ch.commission_amount,
          commission_type: ch.commission_type,
          activation_rate: ch.activation_rate,
          contract_share: ch.contract_share,
          is_active: ch.is_active,
        })),
        totalInvestmentCosts,
        operationalCosts,
        passthroughCosts,
        phaseData,
      };

      setProjectContext(ctx);
      const content = generateAllSections(ctx);
      setGeneratedContent(content);
      return content;
    } catch (error) {
      console.error('Error generating business plan content:', error);
      return null;
    }
  }, [projectId, stepProgress]);

  // Auto-generate on first load
  useEffect(() => {
    if (!loading && projectId && stepProgress) {
      generateContent();
    }
  }, [loading, projectId, stepProgress, generateContent]);

  const saveBusinessPlan = async (data: Partial<BusinessPlanData>) => {
    if (!userId || !projectId) return;

    try {
      const { error } = await supabase
        .from('business_plans')
        .upsert({
          project_id: projectId,
          ...businessPlan,
          ...data,
          updated_at: new Date().toISOString()
        }, {
          onConflict: 'project_id'
        });

      if (error) throw error;

      setBusinessPlan(prev => ({ ...prev, ...data }));
    } catch (error) {
      console.error('Error saving business plan:', error);
      throw error;
    }
  };

  return {
    businessPlan,
    autoGeneratedData,
    generatedContent,
    projectContext,
    loading,
    saveBusinessPlan,
    generateContent,
  };
};
