import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { processSteps, phases } from '@/data/processSteps';
import type { StepProgress } from './useStepProgress';

export interface BusinessPlanSection {
  id: string;
  title: string;
  content: string;
  order: number;
}

export interface BusinessPlanData {
  id?: string;
  project_id?: string;
  executive_summary: string;
  company_description: string;
  market_analysis: string;
  organization: string;
  products_services: string;
  marketing_strategy: string;
  financial_plan: string;
  updated_at?: string;
}

export const useBusinessPlan = (userId: string | undefined, projectId: string | undefined, stepProgress: Record<string, StepProgress>) => {
  const [businessPlan, setBusinessPlan] = useState<BusinessPlanData>({
    executive_summary: '',
    company_description: '',
    market_analysis: '',
    organization: '',
    products_services: '',
    marketing_strategy: '',
    financial_plan: '',
  });
  const [loading, setLoading] = useState(true);
  const [autoGeneratedData, setAutoGeneratedData] = useState<any>(null);

  // Generate data from existing process
  useEffect(() => {
    if (!stepProgress) return;

    const totalSteps = processSteps.length;
    const completedSteps = Object.values(stepProgress).filter(p => p.completed).length;
    const completionRate = totalSteps > 0 ? Math.round((completedSteps / totalSteps) * 100) : 0;

    // Calculate total costs
    let totalCostsMin = 0;
    let totalCostsMax = 0;
    processSteps.forEach(step => {
      if (step.costs) {
        totalCostsMin += step.costs.min;
        totalCostsMax += step.costs.max;
      }
    });

    // Calculate timeline
    const totalDays = processSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
    const completedDays = processSteps
      .filter(step => stepProgress[step.id]?.completed)
      .reduce((sum, step) => sum + step.estimatedDays, 0);

    // Phase analysis
    const phaseData = phases.map(phase => {
      const phaseSteps = processSteps.filter(s => s.phase === phase.id);
      const completed = phaseSteps.filter(s => stepProgress[s.id]?.completed).length;
      const phaseCosts = phaseSteps.reduce((sum, step) => {
        if (step.costs) return sum + ((step.costs.min + step.costs.max) / 2);
        return sum;
      }, 0);
      const phaseDays = phaseSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
      
      return {
        name: phase.name,
        completion: Math.round((completed / phaseSteps.length) * 100),
        costs: phaseCosts,
        days: phaseDays,
        total: phaseSteps.length,
        completed
      };
    });

    setAutoGeneratedData({
      completionRate,
      totalCostsMin,
      totalCostsMax,
      totalDays,
      completedDays,
      completedSteps,
      totalSteps,
      phaseData
    });
  }, [stepProgress]);

  // Load business plan from database
  useEffect(() => {
    if (!userId || !projectId) {
      setLoading(false);
      return;
    }

    const loadBusinessPlan = async () => {
      try {
        const { data, error } = await supabase
          .from('business_plans')
          .select('*')
          .eq('project_id', projectId)
          .maybeSingle();

        if (error && error.code !== 'PGRST116') {
          console.error('Error loading business plan:', error);
        }

        if (data) {
          setBusinessPlan(data);
        }
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setLoading(false);
      }
    };

    loadBusinessPlan();
  }, [userId, projectId]);

  const saveBusinessPlan = async (data: Partial<BusinessPlanData>) => {
    if (!userId || !projectId) return;

    try {
      const { error } = await supabase
        .from('business_plans')
        .upsert({
          project_id: projectId,
          ...businessPlan,
          ...data,
          updated_at: new Date().toISOString()
        }, {
          onConflict: 'project_id'
        });

      if (error) throw error;

      setBusinessPlan(prev => ({ ...prev, ...data }));
    } catch (error) {
      console.error('Error saving business plan:', error);
      throw error;
    }
  };

  return {
    businessPlan,
    autoGeneratedData,
    loading,
    saveBusinessPlan
  };
};
