import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { MarketingPlanData } from './useMarketingPlan';
import type { MarketingPlanIssue } from '@/lib/marketingPlanValidator';
import { addVerificationReportToPDF } from '@/lib/exportVerificationReport';

export const useExportMarketingPlanPDF = () => {
  const exportToPDF = (marketingPlan: MarketingPlanData, autoGeneratedData: any, verificationIssues?: MarketingPlanIssue[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    let yPosition = margin;

    const addFooter = (pageNum: number) => {
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Pagina ${pageNum}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.text(
        `Generato il ${new Date().toLocaleDateString('it-IT')}`,
        margin,
        pageHeight - 10
      );
    };

    const checkNewPage = (requiredSpace: number) => {
      if (yPosition + requiredSpace > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
        return true;
      }
      return false;
    };

    // Cover Page
    doc.setFillColor(168, 85, 247); // Purple gradient
    doc.rect(0, 0, pageWidth, pageHeight / 3, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text('PIANO MARKETING', pageWidth / 2, 60, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text('Strategia Commerciale Energia', pageWidth / 2, 80, { align: 'center' });
    
    doc.setTextColor(100);
    doc.setFontSize(12);
    doc.text(
      `Generato il ${new Date().toLocaleDateString('it-IT', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      })}`,
      pageWidth / 2,
      pageHeight - 40,
      { align: 'center' }
    );

    // Executive Summary Page
    doc.addPage();
    yPosition = margin;
    
    doc.setTextColor(168, 85, 247);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('📊 EXECUTIVE SUMMARY', margin, yPosition);
    yPosition += 20;

    if (autoGeneratedData) {
      // KPI Cards
      const kpis = [
        {
          label: 'Avanzamento Marketing',
          value: `${autoGeneratedData.marketingCompletionRate}%`,
          color: [168, 85, 247]
        },
        {
          label: 'Budget Marketing Stimato',
          value: `€${autoGeneratedData.marketingCostsMin.toLocaleString('it-IT')} - €${autoGeneratedData.marketingCostsMax.toLocaleString('it-IT')}`,
          color: [34, 197, 94]
        },
        {
          label: 'Timeline Attività',
          value: `${autoGeneratedData.marketingDays} giorni`,
          color: [59, 130, 246]
        },
        {
          label: 'Step Marketing',
          value: `${autoGeneratedData.marketingSteps} attività`,
          color: [234, 179, 8]
        }
      ];

      kpis.forEach((kpi, idx) => {
        const col = idx % 2;
        const row = Math.floor(idx / 2);
        const x = margin + col * (pageWidth / 2 - margin);
        const y = yPosition + row * 35;

        doc.setDrawColor(kpi.color[0], kpi.color[1], kpi.color[2]);
        doc.roundedRect(x, y, pageWidth / 2 - margin - 10, 30, 3, 3, 'S');

        doc.setTextColor(kpi.color[0], kpi.color[1], kpi.color[2]);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(kpi.label, x + 5, y + 10);

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(kpi.value, x + 5, y + 22);
      });

      yPosition += 80;
    }

    // Content sections
    const contentSections = [
      {
        title: 'Analisi Mercato Target',
        content: marketingPlan.target_market || 'Da definire',
        icon: '🎯',
        description: 'Identificazione segmenti clientela e dimensione mercato'
      },
      {
        title: 'Strategia di Acquisizione',
        content: marketingPlan.acquisition_strategy || 'Da definire',
        icon: '🚀',
        description: 'Tattiche e canali per acquisizione nuovi clienti'
      },
      {
        title: 'Piano Prezzi',
        content: marketingPlan.pricing_strategy || 'Da definire',
        icon: '💰',
        description: 'Struttura prezzi e offerte commerciali'
      },
      {
        title: 'Posizionamento Competitivo',
        content: marketingPlan.competitive_positioning || 'Da definire',
        icon: '⚡',
        description: 'Differenziazione e vantaggio competitivo'
      },
      {
        title: 'Canali di Comunicazione',
        content: marketingPlan.communication_channels || 'Da definire',
        icon: '📢',
        description: 'Mix di canali e strategie di comunicazione'
      },
      {
        title: 'Allocazione Budget',
        content: marketingPlan.budget_allocation || 'Da definire',
        icon: '💵',
        description: 'Distribuzione investimenti marketing'
      }
    ];

    let currentPage = 2;
    contentSections.forEach((section, index) => {
      doc.addPage();
      addFooter(currentPage++);
      yPosition = margin;

      // Section header with gradient
      doc.setFillColor(168, 85, 247);
      doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(`${section.icon} ${section.title}`, margin + 5, yPosition + 10);
      
      yPosition += 25;

      // Section description
      doc.setTextColor(100);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text(section.description, margin, yPosition);
      yPosition += 15;

      // Section content
      doc.setTextColor(60);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      const lines = doc.splitTextToSize(section.content, pageWidth - 2 * margin);
      lines.forEach((line: string) => {
        if (checkNewPage(10)) {
          addFooter(currentPage++);
        }
        doc.text(line, margin, yPosition);
        yPosition += 7;
      });
    });

    // Recommended Channels Page
    if (autoGeneratedData?.recommendedChannels) {
      doc.addPage();
      addFooter(currentPage++);
      yPosition = margin;

      doc.setFillColor(168, 85, 247);
      doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('📊 Canali Raccomandati', margin + 5, yPosition + 10);
      
      yPosition += 25;

      const tableData = autoGeneratedData.recommendedChannels.map((channel: any) => [
        channel.name,
        channel.priority.toUpperCase(),
        channel.budget
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Canale', 'Priorità', 'Budget Consigliato']],
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: [168, 85, 247],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center'
        },
        styles: {
          fontSize: 11,
          cellPadding: 8
        },
        columnStyles: {
          0: { cellWidth: 70 },
          1: { halign: 'center', cellWidth: 40 },
          2: { halign: 'center', cellWidth: 60 }
        }
      });

      yPosition = (doc as any).lastAutoTable.finalY + 20;

      // Budget Distribution Chart
      if (yPosition > pageHeight - 100) {
        doc.addPage();
        addFooter(currentPage++);
        yPosition = margin;
      }

      doc.setTextColor(60);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Distribuzione Budget Consigliata', margin, yPosition);
      yPosition += 15;

      const colors = [
        [168, 85, 247],  // Purple
        [59, 130, 246],  // Blue
        [34, 197, 94],   // Green
        [234, 179, 8],   // Yellow
        [239, 68, 68]    // Red
      ];

      let startAngle = 0;
      const centerX = pageWidth / 2;
      const centerY = yPosition + 50;
      const radius = 35;

      autoGeneratedData.recommendedChannels.forEach((channel: any, idx: number) => {
        const percentage = parseInt(channel.budget.split('-')[0]);
        const angle = (percentage / 100) * 360;

        doc.setFillColor(colors[idx][0], colors[idx][1], colors[idx][2]);
        
        // Draw pie slice (simplified as a rectangle for this example)
        const x = centerX + radius * Math.cos((startAngle + angle / 2) * Math.PI / 180);
        const y = centerY + radius * Math.sin((startAngle + angle / 2) * Math.PI / 180);
        
        doc.circle(centerX, centerY, radius, 'F');
        
        startAngle += angle;

        // Legend
        const legendY = yPosition + idx * 12;
        doc.setFillColor(colors[idx][0], colors[idx][1], colors[idx][2]);
        doc.rect(margin, legendY, 5, 5, 'F');
        
        doc.setTextColor(60);
        doc.setFontSize(9);
        doc.text(`${channel.name} (${channel.budget})`, margin + 8, legendY + 4);
      });
    }

    // Verification Report
    if (verificationIssues && verificationIssues.length > 0) {
      addVerificationReportToPDF(doc, verificationIssues, [168, 85, 247], currentPage);
    }

    // Save PDF
    const fileName = `piano-marketing-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  };

  return { exportToPDF };
};
