import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { BusinessPlanData } from './useBusinessPlan';
import type { BusinessPlanIssue } from '@/lib/businessPlanValidator';
import { addVerificationReportToPDF } from '@/lib/exportVerificationReport';

export const useExportBusinessPlanPDF = () => {
  const exportToPDF = (businessPlan: BusinessPlanData, autoGeneratedData: any, verificationIssues?: BusinessPlanIssue[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    let yPosition = margin;

    // Helper to add footer
    const addFooter = (pageNum: number) => {
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Pagina ${pageNum}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.text(
        `Generato il ${new Date().toLocaleDateString('it-IT')}`,
        margin,
        pageHeight - 10
      );
    };

    // Helper to check if new page is needed
    const checkNewPage = (requiredSpace: number) => {
      if (yPosition + requiredSpace > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
        return true;
      }
      return false;
    };

    // Cover Page
    doc.setFillColor(59, 130, 246); // Primary blue
    doc.rect(0, 0, pageWidth, pageHeight / 3, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text('BUSINESS PLAN', pageWidth / 2, 60, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text('Società di Vendita Energia', pageWidth / 2, 80, { align: 'center' });
    
    doc.setTextColor(100);
    doc.setFontSize(12);
    doc.text(
      `Generato il ${new Date().toLocaleDateString('it-IT', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      })}`,
      pageWidth / 2,
      pageHeight - 40,
      { align: 'center' }
    );

    // Table of Contents
    doc.addPage();
    yPosition = margin;
    
    doc.setTextColor(59, 130, 246);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('INDICE', margin, yPosition);
    yPosition += 20;

    const sections = [
      { title: '1. Executive Summary', page: 3 },
      { title: '2. Descrizione Società', page: 4 },
      { title: '3. Analisi di Mercato', page: 5 },
      { title: '4. Organizzazione', page: 6 },
      { title: '5. Prodotti e Servizi', page: 7 },
      { title: '6. Strategia di Marketing', page: 8 },
      { title: '7. Piano Finanziario', page: 9 },
      { title: '8. Dati e Grafici', page: 10 }
    ];

    doc.setTextColor(60);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    sections.forEach((section) => {
      doc.text(section.title, margin, yPosition);
      const dots = '...................................................................................................';
      doc.setTextColor(200);
      doc.text(dots, margin + 100, yPosition);
      doc.setTextColor(60);
      doc.text(section.page.toString(), pageWidth - margin, yPosition, { align: 'right' });
      yPosition += 10;
    });

    // Content sections
    const contentSections = [
      {
        title: 'Executive Summary',
        content: businessPlan.executive_summary || 'Da completare',
        icon: '📋'
      },
      {
        title: 'Descrizione Società',
        content: businessPlan.company_description || 'Da completare',
        icon: '🏢'
      },
      {
        title: 'Analisi di Mercato',
        content: businessPlan.market_analysis || 'Da completare',
        icon: '📊'
      },
      {
        title: 'Organizzazione',
        content: businessPlan.organization || 'Da completare',
        icon: '👥'
      },
      {
        title: 'Prodotti e Servizi',
        content: businessPlan.products_services || 'Da completare',
        icon: '🎯'
      },
      {
        title: 'Strategia di Marketing',
        content: businessPlan.marketing_strategy || 'Da completare',
        icon: '📈'
      },
      {
        title: 'Piano Finanziario',
        content: businessPlan.financial_plan || 'Da completare',
        icon: '💰'
      }
    ];

    let currentPage = 3;
    contentSections.forEach((section, index) => {
      doc.addPage();
      addFooter(currentPage++);
      yPosition = margin;

      // Section header
      doc.setFillColor(59, 130, 246);
      doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(`${section.icon} ${index + 1}. ${section.title}`, margin + 5, yPosition + 10);
      
      yPosition += 25;

      // Section content
      doc.setTextColor(60);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      const lines = doc.splitTextToSize(section.content, pageWidth - 2 * margin);
      lines.forEach((line: string) => {
        if (checkNewPage(10)) {
          addFooter(currentPage++);
        }
        doc.text(line, margin, yPosition);
        yPosition += 7;
      });
    });

    // Financial Data & Charts Page
    if (autoGeneratedData) {
      doc.addPage();
      addFooter(currentPage++);
      yPosition = margin;

      doc.setFillColor(59, 130, 246);
      doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('📊 Dati e Analisi Finanziaria', margin + 5, yPosition + 10);
      
      yPosition += 25;

      // Summary Cards
      const summaryData = [
        {
          label: 'Completamento Processo',
          value: `${autoGeneratedData.completionRate}%`,
          color: [34, 197, 94]
        },
        {
          label: 'Investimento Stimato',
          value: `€${autoGeneratedData.totalCostsMin.toLocaleString('it-IT')} - €${autoGeneratedData.totalCostsMax.toLocaleString('it-IT')}`,
          color: [59, 130, 246]
        },
        {
          label: 'Timeline Totale',
          value: `${autoGeneratedData.totalDays} giorni`,
          color: [168, 85, 247]
        },
        {
          label: 'Progresso',
          value: `${autoGeneratedData.completedSteps}/${autoGeneratedData.totalSteps} step`,
          color: [234, 179, 8]
        }
      ];

      summaryData.forEach((item, idx) => {
        const col = idx % 2;
        const row = Math.floor(idx / 2);
        const x = margin + col * (pageWidth / 2 - margin);
        const y = yPosition + row * 35;

        doc.setFillColor(item.color[0], item.color[1], item.color[2]);
        doc.setDrawColor(item.color[0], item.color[1], item.color[2]);
        doc.roundedRect(x, y, pageWidth / 2 - margin - 10, 30, 3, 3, 'S');

        doc.setTextColor(item.color[0], item.color[1], item.color[2]);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(item.label, x + 5, y + 10);

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(item.value, x + 5, y + 22);
      });

      yPosition += 80;

      // Phase Details Table
      if (autoGeneratedData.phaseData && autoGeneratedData.phaseData.length > 0) {
        checkNewPage(60);
        
        doc.setTextColor(60);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Dettaglio Fasi', margin, yPosition);
        yPosition += 10;

        const tableData = autoGeneratedData.phaseData.map((phase: any) => [
          phase.name,
          `${phase.completion}%`,
          `€${Math.round(phase.costs).toLocaleString('it-IT')}`,
          `${phase.days} gg`,
          `${phase.completed}/${phase.total}`
        ]);

        autoTable(doc, {
          startY: yPosition,
          head: [['Fase', 'Completamento', 'Costi Stimati', 'Durata', 'Step']],
          body: tableData,
          theme: 'grid',
          headStyles: {
            fillColor: [59, 130, 246],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center'
          },
          styles: {
            fontSize: 10,
            cellPadding: 5
          },
          columnStyles: {
            0: { cellWidth: 60 },
            1: { halign: 'center' },
            2: { halign: 'right' },
            3: { halign: 'center' },
            4: { halign: 'center' }
          }
        });

        yPosition = (doc as any).lastAutoTable.finalY + 15;

        // Investment Breakdown
        if (yPosition > pageHeight - 80) {
          doc.addPage();
          addFooter(currentPage++);
          yPosition = margin;
        }

        doc.setTextColor(60);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Distribuzione Investimenti per Fase', margin, yPosition);
        yPosition += 10;

        // Simple bar chart representation
        const maxCost = Math.max(...autoGeneratedData.phaseData.map((p: any) => p.costs));
        const chartHeight = 80;
        const barWidth = (pageWidth - 2 * margin - 40) / autoGeneratedData.phaseData.length;

        autoGeneratedData.phaseData.forEach((phase: any, idx: number) => {
          const barHeight = (phase.costs / maxCost) * chartHeight;
          const x = margin + idx * barWidth + 10;
          const y = yPosition + chartHeight - barHeight;

          // Draw bar
          doc.setFillColor(59, 130, 246);
          doc.rect(x, y, barWidth - 5, barHeight, 'F');

          // Draw value on top
          doc.setTextColor(60);
          doc.setFontSize(8);
          doc.text(
            `€${Math.round(phase.costs / 1000)}k`,
            x + (barWidth - 5) / 2,
            y - 3,
            { align: 'center' }
          );

          // Draw phase name below
          doc.setFontSize(7);
          const phaseName = phase.name.length > 12 ? phase.name.substring(0, 12) + '...' : phase.name;
          doc.text(
            phaseName,
            x + (barWidth - 5) / 2,
            yPosition + chartHeight + 8,
            { align: 'center', maxWidth: barWidth - 5 }
          );
        });
      }
    }

    // Verification Report
    if (verificationIssues && verificationIssues.length > 0) {
      addVerificationReportToPDF(doc, verificationIssues, [59, 130, 246], currentPage);
    }

    // Save PDF
    const fileName = `business-plan-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  };

  return { exportToPDF };
};
