import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { processSteps, phases } from '@/data/processSteps';
import type { StepProgress } from './useStepProgress';
import { generateAllMarketingSections } from '@/lib/generateMarketingPlanContent';
import type { ProjectContext } from '@/lib/generateBusinessPlanContent';

export interface MarketingPlanData {
  id?: string;
  project_id?: string;
  target_market: string;
  acquisition_strategy: string;
  pricing_strategy: string;
  competitive_positioning: string;
  communication_channels: string;
  budget_allocation: string;
  project_type?: string;
  updated_at?: string;
}

export const useMarketingPlan = (userId: string | undefined, projectId: string | undefined, stepProgress: Record<string, StepProgress>) => {
  const [marketingPlan, setMarketingPlan] = useState<MarketingPlanData>({
    target_market: '',
    acquisition_strategy: '',
    pricing_strategy: '',
    competitive_positioning: '',
    communication_channels: '',
    budget_allocation: '',
    project_type: 'generale',
  });
  const [loading, setLoading] = useState(true);
  const [autoGeneratedData, setAutoGeneratedData] = useState<any>(null);
  const [generatedContent, setGeneratedContent] = useState<Record<string, string> | null>(null);

  // Generate data from existing process
  useEffect(() => {
    if (!stepProgress) return;

    const totalSteps = processSteps.length;
    const completedSteps = Object.values(stepProgress).filter(p => p.completed).length;
    const completionRate = Math.round((completedSteps / totalSteps) * 100);

    const marketingSteps = processSteps.filter(step => 
      step.category === 'commercial' || 
      step.title.toLowerCase().includes('marketing') ||
      step.title.toLowerCase().includes('commerc')
    );

    const marketingCompletionRate = marketingSteps.length > 0
      ? Math.round((marketingSteps.filter(s => stepProgress[s.id]?.completed).length / marketingSteps.length) * 100)
      : 0;

    let totalCostsMin = 0;
    let totalCostsMax = 0;
    let marketingCostsMin = 0;
    let marketingCostsMax = 0;

    processSteps.forEach(step => {
      if (step.costs) {
        totalCostsMin += step.costs.min;
        totalCostsMax += step.costs.max;
        if (step.category === 'commercial') {
          marketingCostsMin += step.costs.min;
          marketingCostsMax += step.costs.max;
        }
      }
    });

    const totalDays = processSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
    const marketingDays = marketingSteps.reduce((sum, step) => sum + step.estimatedDays, 0);

    const recommendedChannels = [
      { name: 'Digital Marketing', priority: 'high', budget: '30-40%' },
      { name: 'Partnership Commerciali', priority: 'high', budget: '20-30%' },
      { name: 'Direct Sales', priority: 'medium', budget: '15-25%' },
      { name: 'Content Marketing', priority: 'medium', budget: '10-15%' },
      { name: 'Eventi e Fiere', priority: 'low', budget: '5-10%' }
    ];

    setAutoGeneratedData({
      completionRate,
      marketingCompletionRate,
      totalCostsMin,
      totalCostsMax,
      marketingCostsMin,
      marketingCostsMax,
      totalDays,
      marketingDays,
      completedSteps,
      totalSteps,
      marketingSteps: marketingSteps.length,
      recommendedChannels
    });
  }, [stepProgress]);

  // Load marketing plan from database
  useEffect(() => {
    if (!userId || !projectId) {
      setLoading(false);
      return;
    }

    const loadMarketingPlan = async () => {
      try {
        const { data, error } = await supabase
          .from('marketing_plans')
          .select('*')
          .eq('project_id', projectId)
          .maybeSingle();

        if (error && error.code !== 'PGRST116') {
          console.error('Error loading marketing plan:', error);
        }

        if (data) {
          setMarketingPlan(data);
        }
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setLoading(false);
      }
    };

    loadMarketingPlan();
  }, [userId, projectId]);

  // Generate content from project data
  const generateContent = useCallback(async () => {
    if (!projectId || !stepProgress) return null;

    try {
      const [projectRes, simRes, channelsRes, costsRes] = await Promise.all([
        supabase.from('projects').select('*').eq('id', projectId).maybeSingle(),
        supabase.from('project_revenue_simulations').select('*').eq('project_id', projectId).maybeSingle(),
        supabase.from('project_sales_channels').select('*').eq('project_id', projectId),
        supabase.from('project_costs').select('*').eq('project_id', projectId),
      ]);

      const project = projectRes.data;
      const sim = simRes.data;
      const channels = channelsRes.data || [];
      const costs = costsRes.data || [];

      const phaseData = phases.map(phase => {
        const phaseSteps = processSteps.filter(s => s.phase === phase.id);
        const completed = phaseSteps.filter(s => stepProgress[s.id]?.completed).length;
        const phaseCosts = phaseSteps.reduce((sum, step) => {
          if (step.costs) return sum + ((step.costs.min + step.costs.max) / 2);
          return sum;
        }, 0);
        const phaseDays = phaseSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
        return { name: phase.name, completion: Math.round((completed / phaseSteps.length) * 100), costs: phaseCosts, days: phaseDays, total: phaseSteps.length, completed };
      });

      let totalInvestmentCosts = 0;
      processSteps.forEach(step => {
        if (step.costs) totalInvestmentCosts += (step.costs.min + step.costs.max) / 2;
      });

      let operationalCosts = 0;
      let passthroughCosts = 0;
      costs.forEach((c: any) => {
        const total = (c.amount || 0) * (c.quantity || 1);
        if (c.is_passthrough) passthroughCosts += total;
        else operationalCosts += total;
      });

      const ctx: ProjectContext = {
        projectName: project?.name || 'Progetto Reseller',
        projectDescription: project?.description || null,
        commodityType: project?.commodity_type || null,
        marketType: project?.market_type || null,
        regions: project?.regions || null,
        expectedVolumes: project?.expected_volumes || null,
        wholesalerName: project?.wholesaler_name || null,
        plannedStartDate: project?.planned_start_date || null,
        goLiveDate: project?.go_live_date || null,
        stepProgress,
        simulation: sim ? {
          monthlyContracts: (sim.monthly_contracts as number[]) || [30,40,50,60,70,80,90,100,100,100,100,100],
          spreadPerKwh: sim.spread_per_kwh ?? 0.015,
          spreadGasPerSmc: sim.spread_gas_per_smc ?? 0.03,
          ccvMonthly: sim.ccv_monthly ?? 8.5,
          ccvGasMonthly: sim.ccv_gas_monthly ?? 6.5,
          avgMonthlyConsumption: sim.avg_monthly_consumption ?? 200,
          avgMonthlyConsumptionGas: sim.avg_monthly_consumption_gas ?? 80,
          activationRate: sim.activation_rate ?? 85,
          monthlyChurnRate: sim.monthly_churn_rate ?? 1.5,
          clientType: sim.client_type ?? 'domestico',
          commodityType: sim.commodity_type ?? 'luce',
        } : null,
        salesChannels: channels.map((ch: any) => ({
          channel_name: ch.channel_name,
          commission_amount: ch.commission_amount,
          commission_type: ch.commission_type,
          activation_rate: ch.activation_rate,
          contract_share: ch.contract_share,
          is_active: ch.is_active,
        })),
        totalInvestmentCosts,
        operationalCosts,
        passthroughCosts,
        phaseData,
      };

      const content = generateAllMarketingSections(ctx);
      setGeneratedContent(content);
      return content;
    } catch (error) {
      console.error('Error generating marketing plan content:', error);
      return null;
    }
  }, [projectId, stepProgress]);

  // Auto-generate on first load
  useEffect(() => {
    if (!loading && projectId && stepProgress) {
      generateContent();
    }
  }, [loading, projectId, stepProgress, generateContent]);

  const saveMarketingPlan = async (data: Partial<MarketingPlanData>) => {
    if (!userId || !projectId) return;

    try {
      const { error } = await supabase
        .from('marketing_plans')
        .upsert({
          project_id: projectId,
          ...marketingPlan,
          ...data,
          updated_at: new Date().toISOString()
        }, {
          onConflict: 'project_id'
        });

      if (error) throw error;

      setMarketingPlan(prev => ({ ...prev, ...data }));
    } catch (error) {
      console.error('Error saving marketing plan:', error);
      throw error;
    }
  };

  return {
    marketingPlan,
    autoGeneratedData,
    generatedContent,
    loading,
    saveMarketingPlan,
    generateContent,
  };
};
