import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { processSteps, phases } from '@/data/processSteps';
import type { StepProgress } from './useStepProgress';

export interface MarketingPlanData {
  id?: string;
  project_id?: string;
  target_market: string;
  acquisition_strategy: string;
  pricing_strategy: string;
  competitive_positioning: string;
  communication_channels: string;
  budget_allocation: string;
  updated_at?: string;
}

export const useMarketingPlan = (userId: string | undefined, projectId: string | undefined, stepProgress: Record<string, StepProgress>) => {
  const [marketingPlan, setMarketingPlan] = useState<MarketingPlanData>({
    target_market: '',
    acquisition_strategy: '',
    pricing_strategy: '',
    competitive_positioning: '',
    communication_channels: '',
    budget_allocation: '',
  });
  const [loading, setLoading] = useState(true);
  const [autoGeneratedData, setAutoGeneratedData] = useState<any>(null);

  // Generate data from existing process
  useEffect(() => {
    if (!stepProgress) return;

    const totalSteps = processSteps.length;
    const completedSteps = Object.values(stepProgress).filter(p => p.completed).length;
    const completionRate = Math.round((completedSteps / totalSteps) * 100);

    // Calculate marketing-related steps
    const marketingSteps = processSteps.filter(step => 
      step.category === 'commercial' || 
      step.title.toLowerCase().includes('marketing') ||
      step.title.toLowerCase().includes('commerc')
    );

    const marketingCompletionRate = marketingSteps.length > 0
      ? Math.round((marketingSteps.filter(s => stepProgress[s.id]?.completed).length / marketingSteps.length) * 100)
      : 0;

    // Calculate costs
    let totalCostsMin = 0;
    let totalCostsMax = 0;
    let marketingCostsMin = 0;
    let marketingCostsMax = 0;

    processSteps.forEach(step => {
      if (step.costs) {
        totalCostsMin += step.costs.min;
        totalCostsMax += step.costs.max;
        if (step.category === 'commercial') {
          marketingCostsMin += step.costs.min;
          marketingCostsMax += step.costs.max;
        }
      }
    });

    // Timeline data
    const totalDays = processSteps.reduce((sum, step) => sum + step.estimatedDays, 0);
    const marketingDays = marketingSteps.reduce((sum, step) => sum + step.estimatedDays, 0);

    // Channel recommendations based on process
    const recommendedChannels = [
      { name: 'Digital Marketing', priority: 'high', budget: '30-40%' },
      { name: 'Partnership Commerciali', priority: 'high', budget: '20-30%' },
      { name: 'Direct Sales', priority: 'medium', budget: '15-25%' },
      { name: 'Content Marketing', priority: 'medium', budget: '10-15%' },
      { name: 'Eventi e Fiere', priority: 'low', budget: '5-10%' }
    ];

    setAutoGeneratedData({
      completionRate,
      marketingCompletionRate,
      totalCostsMin,
      totalCostsMax,
      marketingCostsMin,
      marketingCostsMax,
      totalDays,
      marketingDays,
      completedSteps,
      totalSteps,
      marketingSteps: marketingSteps.length,
      recommendedChannels
    });
  }, [stepProgress]);

  // Load marketing plan from database
  useEffect(() => {
    if (!userId || !projectId) {
      setLoading(false);
      return;
    }

    const loadMarketingPlan = async () => {
      try {
        const { data, error } = await supabase
          .from('marketing_plans')
          .select('*')
          .eq('project_id', projectId)
          .maybeSingle();

        if (error && error.code !== 'PGRST116') {
          console.error('Error loading marketing plan:', error);
        }

        if (data) {
          setMarketingPlan(data);
        }
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setLoading(false);
      }
    };

    loadMarketingPlan();
  }, [userId, projectId]);

  const saveMarketingPlan = async (data: Partial<MarketingPlanData>) => {
    if (!userId || !projectId) return;

    try {
      const { error } = await supabase
        .from('marketing_plans')
        .upsert({
          project_id: projectId,
          ...marketingPlan,
          ...data,
          updated_at: new Date().toISOString()
        }, {
          onConflict: 'project_id'
        });

      if (error) throw error;

      setMarketingPlan(prev => ({ ...prev, ...data }));
    } catch (error) {
      console.error('Error saving marketing plan:', error);
      throw error;
    }
  };

  return {
    marketingPlan,
    autoGeneratedData,
    loading,
    saveMarketingPlan
  };
};
