import { useState, useMemo } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useBusinessPlan } from '@/hooks/useBusinessPlan';
import { useExportBusinessPlanPDF } from '@/hooks/useExportBusinessPlanPDF';
import { exportBusinessPlanToDocx } from '@/lib/exportBusinessPlanDocx';
import type { StepProgress } from '@/hooks/useStepProgress';
import { Save, FileText, TrendingUp, Users, Target, DollarSign, Calendar, Download, Wand2, RefreshCw, FileDown } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';
import { BusinessPlanVerification } from './BusinessPlanVerification';
import { validateBusinessPlan } from '@/lib/businessPlanValidator';

interface BusinessPlanEditorProps {
  userId: string;
  projectId: string;
  stepProgress: Record<string, StepProgress>;
}

export const BusinessPlanEditor = ({ userId, projectId, stepProgress }: BusinessPlanEditorProps) => {
  const { businessPlan, autoGeneratedData, generatedContent, projectContext, loading, saveBusinessPlan, generateContent } = useBusinessPlan(userId, projectId, stepProgress);
  const { exportToPDF } = useExportBusinessPlanPDF();
  const { toast } = useToast();
  const [activeSection, setActiveSection] = useState('executive_summary');
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);

  const sections = [
    { id: 'executive_summary', label: 'Executive Summary', icon: FileText, description: 'Sintesi del progetto imprenditoriale' },
    { id: 'company_description', label: 'Descrizione Società', icon: Users, description: 'Struttura societaria e organizzativa' },
    { id: 'market_analysis', label: 'Analisi Mercato', icon: TrendingUp, description: 'Analisi mercato energia e target' },
    { id: 'organization', label: 'Organizzazione', icon: Users, description: 'Struttura organizzativa e team' },
    { id: 'products_services', label: 'Prodotti e Servizi', icon: Target, description: 'Offerta commerciale' },
    { id: 'marketing_strategy', label: 'Strategia Marketing', icon: TrendingUp, description: 'Piano di marketing e vendite' },
    { id: 'financial_plan', label: 'Piano Finanziario', icon: DollarSign, description: 'Previsioni economico-finanziarie' },
  ];

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveBusinessPlan(editedContent);
      setEditedContent({});
      toast({ title: 'Business Plan salvato', description: 'Le modifiche sono state salvate con successo.' });
    } catch {
      toast({ title: 'Errore', description: 'Impossibile salvare il business plan.', variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateAll = async () => {
    setGenerating(true);
    try {
      const content = await generateContent();
      if (content) {
        setEditedContent(content);
        toast({ title: 'Contenuti generati', description: 'Tutti i contenuti sono stati generati dai dati del progetto. Puoi modificarli e poi salvare.' });
      } else {
        toast({ title: 'Errore', description: 'Impossibile generare i contenuti. Verifica che il progetto abbia dati sufficienti.', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Errore', description: 'Errore durante la generazione.', variant: 'destructive' });
    } finally {
      setGenerating(false);
    }
  };

  const handleGenerateSection = async (sectionId: string) => {
    setGenerating(true);
    try {
      const content = await generateContent();
      if (content && content[sectionId]) {
        setEditedContent(prev => ({ ...prev, [sectionId]: content[sectionId] }));
        toast({ title: 'Sezione generata', description: `"${sections.find(s => s.id === sectionId)?.label}" è stata generata dai dati del progetto.` });
      }
    } catch {
      toast({ title: 'Errore', description: 'Errore durante la generazione.', variant: 'destructive' });
    } finally {
      setGenerating(false);
    }
  };

  const getContent = (sectionId: string) => {
    // Priority: user edits > saved content > auto-generated
    if (editedContent[sectionId] !== undefined) return editedContent[sectionId];
    const saved = businessPlan[sectionId as keyof typeof businessPlan];
    if (saved && typeof saved === 'string' && saved.trim()) return saved;
    if (generatedContent?.[sectionId]) return generatedContent[sectionId];
    return '';
  };

  const getSectionStatus = (sectionId: string): 'saved' | 'edited' | 'auto' | 'empty' => {
    if (editedContent[sectionId] !== undefined) return 'edited';
    const saved = businessPlan[sectionId as keyof typeof businessPlan];
    if (saved && typeof saved === 'string' && saved.trim()) return 'saved';
    if (generatedContent?.[sectionId]) return 'auto';
    return 'empty';
  };

  const statusBadge = (status: 'saved' | 'edited' | 'auto' | 'empty') => {
    switch (status) {
      case 'saved': return <Badge variant="default">Salvato</Badge>;
      case 'edited': return <Badge variant="secondary">Non salvato</Badge>;
      case 'auto': return <Badge variant="outline" className="border-primary text-primary">Auto-generato</Badge>;
      case 'empty': return <Badge variant="outline" className="text-muted-foreground">Vuoto</Badge>;
    }
  };

  const validationIssues = useMemo(() => {
    if (!projectContext) return [];
    return validateBusinessPlan(projectContext);
  }, [projectContext]);

  const hasUnsavedChanges = Object.keys(editedContent).length > 0;

  const handleExportPDF = () => {
    try {
      // Use displayed content for export
      const contentForExport: any = { ...businessPlan };
      Object.keys(editedContent).forEach(key => {
        (contentForExport as any)[key] = editedContent[key];
      });
      // Fill with generated content where empty
      if (generatedContent) {
        sections.forEach(s => {
          if (!contentForExport[s.id] && generatedContent[s.id]) {
            contentForExport[s.id] = generatedContent[s.id];
          }
        });
      }
      exportToPDF(contentForExport, autoGeneratedData, validationIssues);
      toast({ title: 'PDF esportato', description: 'Il Business Plan è stato esportato con successo.' });
    } catch {
      toast({ title: 'Errore', description: 'Impossibile esportare il PDF.', variant: 'destructive' });
    }
  };

  const handleExportDocx = async () => {
    try {
      const contentForExport: any = { ...businessPlan };
      Object.keys(editedContent).forEach(key => {
        (contentForExport as any)[key] = editedContent[key];
      });
      if (generatedContent) {
        sections.forEach(s => {
          if (!contentForExport[s.id] && generatedContent[s.id]) {
            contentForExport[s.id] = generatedContent[s.id];
          }
        });
      }
      await exportBusinessPlanToDocx(contentForExport, autoGeneratedData, generatedContent, validationIssues);
      toast({ title: 'Word esportato', description: 'Il Business Plan è stato esportato in formato .docx.' });
    } catch {
      toast({ title: 'Errore', description: 'Impossibile esportare il file Word.', variant: 'destructive' });
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-muted-foreground">Caricamento business plan...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-gradient-subtle border-border/50">
        <CardHeader>
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <CardTitle className="text-2xl">Business Plan</CardTitle>
              <CardDescription>
                Piano strategico generato automaticamente dai dati del progetto — modificabile in ogni sezione
              </CardDescription>
            </div>
            <div className="flex items-center gap-2 flex-wrap">
              <Button onClick={handleGenerateAll} variant="outline" disabled={generating}>
                {generating ? <RefreshCw className="h-4 w-4 mr-2 animate-spin" /> : <Wand2 className="h-4 w-4 mr-2" />}
                {generating ? 'Generazione...' : 'Genera / Rigenera Tutto'}
              </Button>
              <Button onClick={handleExportPDF} variant="outline">
                <Download className="h-4 w-4 mr-2" />
                PDF
              </Button>
              <Button onClick={handleExportDocx} variant="outline">
                <FileDown className="h-4 w-4 mr-2" />
                Word
              </Button>
              <Button onClick={handleSave} disabled={!hasUnsavedChanges || saving}>
                <Save className="h-4 w-4 mr-2" />
                {saving ? 'Salvataggio...' : 'Salva Modifiche'}
              </Button>
            </div>
          </div>
        </CardHeader>
        {autoGeneratedData && (
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Avanzamento</span>
                </div>
                <div className="text-2xl font-bold">{autoGeneratedData.completionRate}%</div>
                <div className="text-xs text-muted-foreground mt-1">
                  {autoGeneratedData.completedSteps}/{autoGeneratedData.totalSteps} step completati
                </div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Calendar className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Timeline</span>
                </div>
                <div className="text-2xl font-bold">{autoGeneratedData.totalDays} gg</div>
                <div className="text-xs text-muted-foreground mt-1">
                  {autoGeneratedData.completedDays} giorni completati
                </div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Investimento Min</span>
                </div>
                <div className="text-2xl font-bold">€{autoGeneratedData.totalCostsMin.toLocaleString()}</div>
                <div className="text-xs text-muted-foreground mt-1">costi stimati</div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Investimento Max</span>
                </div>
                <div className="text-2xl font-bold">€{autoGeneratedData.totalCostsMax.toLocaleString()}</div>
                <div className="text-xs text-muted-foreground mt-1">costi stimati</div>
              </div>
            </div>
          </CardContent>
        )}
      </Card>

      {/* Verification Panel */}
      <BusinessPlanVerification 
        issues={validationIssues} 
        onNavigateToSection={(sectionId) => setActiveSection(sectionId)} 
      />

      {/* Section status overview */}
      <div className="flex flex-wrap gap-2 items-center">
        <span className="text-sm text-muted-foreground mr-2">Stato sezioni:</span>
        {sections.map(s => {
          const status = getSectionStatus(s.id);
          return (
            <button
              key={s.id}
              onClick={() => setActiveSection(s.id)}
              className={`text-xs px-2 py-1 rounded-md border transition-colors ${
                activeSection === s.id ? 'border-primary bg-primary/10' : 'border-border hover:border-primary/50'
              }`}
            >
              <span className="mr-1">{s.label}</span>
              {status === 'saved' && <span className="text-primary">✓</span>}
              {status === 'edited' && <span className="text-accent-foreground">●</span>}
              {status === 'auto' && <span className="text-primary">●</span>}
              {status === 'empty' && <span className="text-muted-foreground">○</span>}
            </button>
          );
        })}
      </div>

      {/* Editor sections */}
      <Tabs value={activeSection} onValueChange={setActiveSection} className="space-y-4">
        <TabsList className="grid grid-cols-3 lg:grid-cols-7 h-auto">
          {sections.map((section) => (
            <TabsTrigger key={section.id} value={section.id} className="flex-col gap-1 py-2">
              <section.icon className="h-4 w-4" />
              <span className="text-xs hidden lg:inline">{section.label}</span>
            </TabsTrigger>
          ))}
        </TabsList>

        {sections.map((section) => {
          const status = getSectionStatus(section.id);
          return (
            <TabsContent key={section.id} value={section.id} className="space-y-4">
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        <section.icon className="h-5 w-5" />
                        {section.label}
                      </CardTitle>
                      <CardDescription>{section.description}</CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      {statusBadge(status)}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleGenerateSection(section.id)}
                        disabled={generating}
                        title="Rigenera questa sezione dai dati del progetto"
                      >
                        {generating ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
                        <span className="ml-1 hidden sm:inline">Rigenera</span>
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea
                    value={getContent(section.id)}
                    onChange={(e) => setEditedContent({ ...editedContent, [section.id]: e.target.value })}
                    placeholder="Clicca 'Genera / Rigenera Tutto' per popolare automaticamente questa sezione..."
                    className="min-h-[400px] font-mono text-sm leading-relaxed"
                  />
                  
                  {status === 'auto' && (
                    <div className="mt-3 p-3 bg-muted/50 rounded-lg border border-border">
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <Wand2 className="h-3 w-3" />
                        Contenuto generato automaticamente dai dati del progetto. Modificalo liberamente, poi premi "Salva Modifiche" per renderlo permanente.
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
          );
        })}
      </Tabs>
    </div>
  );
};
