import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useBusinessPlan } from '@/hooks/useBusinessPlan';
import type { StepProgress } from '@/hooks/useStepProgress';
import { Save, FileText, TrendingUp, Users, Target, DollarSign, Calendar } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';

interface BusinessPlanEditorProps {
  userId: string;
  projectId: string;
  stepProgress: Record<string, StepProgress>;
}

export const BusinessPlanEditor = ({ userId, projectId, stepProgress }: BusinessPlanEditorProps) => {
  const { businessPlan, autoGeneratedData, loading, saveBusinessPlan } = useBusinessPlan(userId, projectId, stepProgress);
  const { toast } = useToast();
  const [activeSection, setActiveSection] = useState('summary');
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);

  const sections = [
    {
      id: 'executive_summary',
      label: 'Executive Summary',
      icon: FileText,
      description: 'Sintesi del progetto imprenditoriale',
      placeholder: 'Descrizione generale del progetto, obiettivi principali e fattori chiave di successo...'
    },
    {
      id: 'company_description',
      label: 'Descrizione Società',
      icon: Users,
      description: 'Struttura societaria e organizzativa',
      placeholder: 'Forma giuridica, capitale sociale, sede legale, organigramma...'
    },
    {
      id: 'market_analysis',
      label: 'Analisi Mercato',
      icon: TrendingUp,
      description: 'Analisi mercato energia e target',
      placeholder: 'Dimensione mercato, trend, target clienti, competitor...'
    },
    {
      id: 'organization',
      label: 'Organizzazione',
      icon: Users,
      description: 'Struttura organizzativa e team',
      placeholder: 'Risorse umane, competenze chiave, consulenti esterni...'
    },
    {
      id: 'products_services',
      label: 'Prodotti e Servizi',
      icon: Target,
      description: 'Offerta commerciale',
      placeholder: 'Prodotti energia elettrica, servizi aggiuntivi, pacchetti...'
    },
    {
      id: 'marketing_strategy',
      label: 'Strategia Marketing',
      icon: TrendingUp,
      description: 'Piano di marketing e vendite',
      placeholder: 'Canali acquisizione, strategia comunicazione, partnership...'
    },
    {
      id: 'financial_plan',
      label: 'Piano Finanziario',
      icon: DollarSign,
      description: 'Previsioni economico-finanziarie',
      placeholder: 'Investimenti iniziali, ricavi previsti, break-even point...'
    }
  ];

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveBusinessPlan(editedContent);
      setEditedContent({});
      toast({
        title: 'Business Plan salvato',
        description: 'Le modifiche sono state salvate con successo.'
      });
    } catch (error) {
      toast({
        title: 'Errore',
        description: 'Impossibile salvare il business plan.',
        variant: 'destructive'
      });
    } finally {
      setSaving(false);
    }
  };

  const getContent = (sectionId: string) => {
    return editedContent[sectionId] ?? businessPlan[sectionId as keyof typeof businessPlan] ?? '';
  };

  const hasUnsavedChanges = Object.keys(editedContent).length > 0;

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-muted-foreground">Caricamento business plan...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with auto-generated insights */}
      <Card className="bg-gradient-subtle border-border/50">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-2xl">Business Plan</CardTitle>
              <CardDescription>
                Piano strategico integrato con i dati del progetto operativo
              </CardDescription>
            </div>
            <Button onClick={handleSave} disabled={!hasUnsavedChanges || saving}>
              <Save className="h-4 w-4 mr-2" />
              {saving ? 'Salvataggio...' : 'Salva Modifiche'}
            </Button>
          </div>
        </CardHeader>
        {autoGeneratedData && (
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Avanzamento</span>
                </div>
                <div className="text-2xl font-bold">{autoGeneratedData.completionRate}%</div>
                <div className="text-xs text-muted-foreground mt-1">
                  {autoGeneratedData.completedSteps}/{autoGeneratedData.totalSteps} step completati
                </div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Calendar className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Timeline</span>
                </div>
                <div className="text-2xl font-bold">{autoGeneratedData.totalDays} gg</div>
                <div className="text-xs text-muted-foreground mt-1">
                  {autoGeneratedData.completedDays} giorni completati
                </div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Investimento Min</span>
                </div>
                <div className="text-2xl font-bold">€{autoGeneratedData.totalCostsMin.toLocaleString()}</div>
                <div className="text-xs text-muted-foreground mt-1">costi stimati</div>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">Investimento Max</span>
                </div>
                <div className="text-2xl font-bold">€{autoGeneratedData.totalCostsMax.toLocaleString()}</div>
                <div className="text-xs text-muted-foreground mt-1">costi stimati</div>
              </div>
            </div>
          </CardContent>
        )}
      </Card>

      {/* Editor sections */}
      <Tabs value={activeSection} onValueChange={setActiveSection} className="space-y-4">
        <TabsList className="grid grid-cols-3 lg:grid-cols-7 h-auto">
          {sections.map((section) => (
            <TabsTrigger key={section.id} value={section.id} className="flex-col gap-1 py-2">
              <section.icon className="h-4 w-4" />
              <span className="text-xs hidden lg:inline">{section.label}</span>
            </TabsTrigger>
          ))}
        </TabsList>

        {sections.map((section) => (
          <TabsContent key={section.id} value={section.id} className="space-y-4">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      <section.icon className="h-5 w-5" />
                      {section.label}
                    </CardTitle>
                    <CardDescription>{section.description}</CardDescription>
                  </div>
                  {editedContent[section.id] && (
                    <Badge variant="secondary">Non salvato</Badge>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={getContent(section.id)}
                  onChange={(e) => setEditedContent({ ...editedContent, [section.id]: e.target.value })}
                  placeholder={section.placeholder}
                  className="min-h-[400px] font-mono text-sm"
                />
                
                {/* Auto-generated suggestions based on section */}
                {section.id === 'financial_plan' && autoGeneratedData && (
                  <div className="mt-4 p-4 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold mb-2">Dati dal Piano Operativo:</h4>
                    <ul className="space-y-1 text-sm text-muted-foreground">
                      <li>• Investimento iniziale stimato: €{autoGeneratedData.totalCostsMin.toLocaleString()} - €{autoGeneratedData.totalCostsMax.toLocaleString()}</li>
                      <li>• Timeline implementazione: {autoGeneratedData.totalDays} giorni</li>
                      {autoGeneratedData.phaseData.map((phase: any, idx: number) => (
                        <li key={idx}>
                          • Fase {idx + 1} ({phase.name}): €{Math.round(phase.costs).toLocaleString()} - {phase.days} giorni
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
};
