import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useMarketingPlan } from '@/hooks/useMarketingPlan';
import { useExportMarketingPlanPDF } from '@/hooks/useExportMarketingPlanPDF';
import type { StepProgress } from '@/hooks/useStepProgress';
import { Save, Target, TrendingUp, Users, DollarSign, Megaphone, Download, Lightbulb } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';

interface MarketingPlanEditorProps {
  userId: string;
  projectId: string;
  stepProgress: Record<string, StepProgress>;
}

export const MarketingPlanEditor = ({ userId, projectId, stepProgress }: MarketingPlanEditorProps) => {
  const { marketingPlan, autoGeneratedData, loading, saveMarketingPlan } = useMarketingPlan(userId, projectId, stepProgress);
  const { exportToPDF } = useExportMarketingPlanPDF();
  const { toast } = useToast();
  const [activeSection, setActiveSection] = useState('target');
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);

  const sections = [
    {
      id: 'target_market',
      label: 'Mercato Target',
      icon: Target,
      description: 'Segmentazione clientela e dimensione mercato',
      placeholder: 'Descrivi i segmenti di clientela target (residenziale, PMI, grandi clienti), dimensione del mercato, potenziale di crescita...'
    },
    {
      id: 'acquisition_strategy',
      label: 'Strategia Acquisizione',
      icon: TrendingUp,
      description: 'Tattiche per acquisire nuovi clienti',
      placeholder: 'Definisci le tattiche di acquisizione, funnel di conversione, partnership strategiche, programmi referral...'
    },
    {
      id: 'pricing_strategy',
      label: 'Piano Prezzi',
      icon: DollarSign,
      description: 'Struttura prezzi e offerte',
      placeholder: 'Definisci la strategia pricing: tariffe base, offerte promozionali, pacchetti, sconti volume, condizioni pagamento...'
    },
    {
      id: 'competitive_positioning',
      label: 'Posizionamento',
      icon: Lightbulb,
      description: 'Vantaggio competitivo',
      placeholder: 'Descrivi il posizionamento vs concorrenti: USP, differenziatori, vantaggi competitivi, barriere all\'entrata...'
    },
    {
      id: 'communication_channels',
      label: 'Canali Comunicazione',
      icon: Megaphone,
      description: 'Mix canali marketing',
      placeholder: 'Elenca i canali: digital marketing, social media, email, content marketing, eventi, direct sales, partnership...'
    },
    {
      id: 'budget_allocation',
      label: 'Budget Marketing',
      icon: DollarSign,
      description: 'Allocazione investimenti',
      placeholder: 'Definisci la distribuzione del budget per canale, KPI target, ROI atteso, investimenti mensili/annuali...'
    }
  ];

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveMarketingPlan(editedContent);
      setEditedContent({});
      toast({
        title: 'Piano Marketing salvato',
        description: 'Le modifiche sono state salvate con successo.'
      });
    } catch (error) {
      toast({
        title: 'Errore',
        description: 'Impossibile salvare il piano marketing.',
        variant: 'destructive'
      });
    } finally {
      setSaving(false);
    }
  };

  const getContent = (sectionId: string) => {
    return editedContent[sectionId] ?? marketingPlan[sectionId as keyof typeof marketingPlan] ?? '';
  };

  const hasUnsavedChanges = Object.keys(editedContent).length > 0;

  const handleExportPDF = () => {
    try {
      exportToPDF(marketingPlan, autoGeneratedData);
      toast({
        title: 'PDF esportato',
        description: 'Il Piano Marketing è stato esportato con successo.'
      });
    } catch (error) {
      toast({
        title: 'Errore',
        description: 'Impossibile esportare il PDF.',
        variant: 'destructive'
      });
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-muted-foreground">Caricamento piano marketing...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with auto-generated insights */}
      <Card className="bg-gradient-subtle border-border/50">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-2xl">Piano Marketing</CardTitle>
              <CardDescription>
                Strategia commerciale integrata con i dati del progetto
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={handleExportPDF} variant="outline">
                <Download className="h-4 w-4 mr-2" />
                Esporta PDF
              </Button>
              <Button onClick={handleSave} disabled={!hasUnsavedChanges || saving}>
                <Save className="h-4 w-4 mr-2" />
                {saving ? 'Salvataggio...' : 'Salva'}
              </Button>
            </div>
          </div>
        </CardHeader>
        {autoGeneratedData && (
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="h-5 w-5 text-primary" />
                  <span className="text-sm font-medium">Avanzamento</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingCompletionRate}%</p>
                <p className="text-xs text-muted-foreground">Attività marketing</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-5 w-5 text-green-500" />
                  <span className="text-sm font-medium">Budget Stimato</span>
                </div>
                <p className="text-lg font-bold">
                  €{autoGeneratedData.marketingCostsMin.toLocaleString('it-IT')} - €{autoGeneratedData.marketingCostsMax.toLocaleString('it-IT')}
                </p>
                <p className="text-xs text-muted-foreground">Investimento marketing</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="h-5 w-5 text-purple-500" />
                  <span className="text-sm font-medium">Timeline</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingDays}</p>
                <p className="text-xs text-muted-foreground">giorni stimati</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Target className="h-5 w-5 text-orange-500" />
                  <span className="text-sm font-medium">Attività</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingSteps}</p>
                <p className="text-xs text-muted-foreground">step marketing</p>
              </div>
            </div>

            {/* Recommended Channels */}
            {autoGeneratedData.recommendedChannels && (
              <div className="mt-6">
                <h4 className="text-sm font-semibold mb-3">Canali Raccomandati</h4>
                <div className="grid grid-cols-1 md:grid-cols-5 gap-2">
                  {autoGeneratedData.recommendedChannels.map((channel: any, idx: number) => (
                    <div key={idx} className="bg-background/50 rounded-lg p-3 border border-border/50">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-medium">{channel.name}</span>
                        <Badge variant={channel.priority === 'high' ? 'default' : 'secondary'} className="text-xs">
                          {channel.priority}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{channel.budget}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        )}
      </Card>

      {/* Sections Tabs */}
      <Card>
        <Tabs value={activeSection} onValueChange={setActiveSection}>
          <CardHeader className="pb-3">
            <TabsList className="grid w-full grid-cols-3 lg:grid-cols-6">
              {sections.map((section) => (
                <TabsTrigger key={section.id} value={section.id} className="gap-2">
                  <section.icon className="h-4 w-4" />
                  <span className="hidden sm:inline">{section.label}</span>
                </TabsTrigger>
              ))}
            </TabsList>
          </CardHeader>

          {sections.map((section) => (
            <TabsContent key={section.id} value={section.id}>
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        <section.icon className="h-5 w-5" />
                        {section.label}
                      </CardTitle>
                      <CardDescription>{section.description}</CardDescription>
                    </div>
                    {editedContent[section.id] !== undefined && (
                      <Badge variant="secondary">Non salvato</Badge>
                    )}
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea
                    value={getContent(section.id)}
                    onChange={(e) => setEditedContent(prev => ({ ...prev, [section.id]: e.target.value }))}
                    placeholder={section.placeholder}
                    className="min-h-[400px] font-mono text-sm"
                  />
                </CardContent>
              </Card>
            </TabsContent>
          ))}
        </Tabs>
      </Card>
    </div>
  );
};
