import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useMarketingPlan } from '@/hooks/useMarketingPlan';
import { useExportMarketingPlanPDF } from '@/hooks/useExportMarketingPlanPDF';
import type { StepProgress } from '@/hooks/useStepProgress';
import { Save, Target, TrendingUp, Users, DollarSign, Megaphone, Download, Lightbulb, Sparkles, RefreshCw, Wand2, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { MarketingPlanVerification } from '@/components/MarketingPlanVerification';
import { validateMarketingPlan } from '@/lib/marketingPlanValidator';
import { exportMarketingPlanToDocx } from '@/lib/exportMarketingPlanDocx';

interface MarketingPlanEditorProps {
  userId: string;
  projectId: string;
  stepProgress: Record<string, StepProgress>;
}

export const MarketingPlanEditor = ({ userId, projectId, stepProgress }: MarketingPlanEditorProps) => {
  const { marketingPlan, autoGeneratedData, generatedContent, projectContext, loading, saveMarketingPlan, generateContent } = useMarketingPlan(userId, projectId, stepProgress);
  const { exportToPDF } = useExportMarketingPlanPDF();
  const { toast } = useToast();
  const [activeSection, setActiveSection] = useState('target_market');
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [generatingAI, setGeneratingAI] = useState<string | null>(null);
  const [generatingAll, setGeneratingAll] = useState(false);
  const [projectType, setProjectType] = useState<string>(marketingPlan.project_type || 'generale');
  const [validationResults, setValidationResults] = useState<Record<string, { isValid: boolean; confidence: number; missingKeywords: string[] }>>({});

  const sections = [
    {
      id: 'target_market',
      label: 'Mercato Target',
      icon: Target,
      description: 'Segmentazione clientela e dimensione mercato',
      placeholder: 'Descrivi i segmenti di clientela target (residenziale, PMI, grandi clienti), dimensione del mercato, potenziale di crescita...'
    },
    {
      id: 'acquisition_strategy',
      label: 'Strategia Acquisizione',
      icon: TrendingUp,
      description: 'Tattiche per acquisire nuovi clienti',
      placeholder: 'Definisci le tattiche di acquisizione, funnel di conversione, partnership strategiche, programmi referral...'
    },
    {
      id: 'pricing_strategy',
      label: 'Piano Prezzi',
      icon: DollarSign,
      description: 'Struttura prezzi e offerte',
      placeholder: 'Definisci la strategia pricing: tariffe base, offerte promozionali, pacchetti, sconti volume, condizioni pagamento...'
    },
    {
      id: 'competitive_positioning',
      label: 'Posizionamento',
      icon: Lightbulb,
      description: 'Vantaggio competitivo',
      placeholder: 'Descrivi il posizionamento vs concorrenti: USP, differenziatori, vantaggi competitivi, barriere all\'entrata...'
    },
    {
      id: 'communication_channels',
      label: 'Canali Comunicazione',
      icon: Megaphone,
      description: 'Mix canali marketing',
      placeholder: 'Elenca i canali: digital marketing, social media, email, content marketing, eventi, direct sales, partnership...'
    },
    {
      id: 'budget_allocation',
      label: 'Budget Marketing',
      icon: DollarSign,
      description: 'Allocazione investimenti',
      placeholder: 'Definisci la distribuzione del budget per canale, KPI target, ROI atteso, investimenti mensili/annuali...'
    }
  ];

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveMarketingPlan({ ...editedContent, project_type: projectType });
      setEditedContent({});
      toast({
        title: 'Piano Marketing salvato',
        description: 'Le modifiche sono state salvate con successo.'
      });
    } catch (error) {
      toast({
        title: 'Errore',
        description: 'Impossibile salvare il piano marketing.',
        variant: 'destructive'
      });
    } finally {
      setSaving(false);
    }
  };

  const getContent = (sectionId: string) => {
    if (editedContent[sectionId] !== undefined) return editedContent[sectionId];
    const saved = marketingPlan[sectionId as keyof typeof marketingPlan];
    if (saved && typeof saved === 'string' && saved.trim()) return saved;
    if (generatedContent?.[sectionId]) return generatedContent[sectionId];
    return '';
  };

  const getSectionStatus = (sectionId: string): 'saved' | 'edited' | 'auto' | 'empty' => {
    if (editedContent[sectionId] !== undefined) return 'edited';
    const saved = marketingPlan[sectionId as keyof typeof marketingPlan];
    if (saved && typeof saved === 'string' && saved.trim()) return 'saved';
    if (generatedContent?.[sectionId]) return 'auto';
    return 'empty';
  };

  const handleGenerateAll = async () => {
    setGeneratingAll(true);
    try {
      const content = await generateContent();
      if (content) {
        setEditedContent(content);
        toast({ title: 'Contenuti generati', description: 'Tutti i contenuti sono stati generati dai dati del progetto. Puoi modificarli e poi salvare.' });
      } else {
        toast({ title: 'Errore', description: 'Impossibile generare i contenuti.', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Errore', description: 'Errore durante la generazione.', variant: 'destructive' });
    } finally {
      setGeneratingAll(false);
    }
  };

  const handleGenerateSection = async (sectionId: string) => {
    setGeneratingAll(true);
    try {
      const content = await generateContent();
      if (content && content[sectionId]) {
        setEditedContent(prev => ({ ...prev, [sectionId]: content[sectionId] }));
        toast({ title: 'Sezione generata', description: `"${sections.find(s => s.id === sectionId)?.label}" è stata generata dai dati del progetto.` });
      }
    } catch {
      toast({ title: 'Errore', description: 'Errore durante la generazione.', variant: 'destructive' });
    } finally {
      setGeneratingAll(false);
    }
  };

  const hasUnsavedChanges = Object.keys(editedContent).length > 0;

  // Validate existing content when loaded
  useEffect(() => {
    if (!marketingPlan || !projectType) return;
    
    const newValidationResults: Record<string, { isValid: boolean; confidence: number; missingKeywords: string[] }> = {};
    
    sections.forEach(section => {
      const content = marketingPlan[section.id as keyof typeof marketingPlan];
      if (content && typeof content === 'string' && content.trim().length > 50) {
        newValidationResults[section.id] = validateContent(content, projectType);
      }
    });
    
    setValidationResults(newValidationResults);
  }, [marketingPlan, projectType]);

  const validateContent = (content: string, selectedProjectType: string): { isValid: boolean; confidence: number; missingKeywords: string[] } => {
    if (!content || content.trim().length < 50) {
      return { isValid: false, confidence: 0, missingKeywords: [] };
    }

    const contentLower = content.toLowerCase();
    
    const projectKeywords: Record<string, string[]> = {
      solare: ['solare', 'fotovoltaic', 'pannelli', 'moduli', 'inverter', 'irraggiamento', 'kwp', 'kwh'],
      eolico: ['eolico', 'turbine', 'aerogeneratore', 'vento', 'pale', 'rotore', 'offshore', 'onshore'],
      efficienza_energetica: ['efficienza', 'riqualificazione', 'risparmio energetico', 'isolamento', 'cappotto termico', 'pompa di calore', 'climatizzazione'],
      generale: ['energia', 'rinnovabili', 'sostenibile', 'green', 'emissioni', 'elettrico']
    };

    const keywords = projectKeywords[selectedProjectType] || projectKeywords.generale;
    const foundKeywords = keywords.filter(keyword => contentLower.includes(keyword));
    const missingKeywords = keywords.filter(keyword => !contentLower.includes(keyword));
    
    const confidence = Math.round((foundKeywords.length / keywords.length) * 100);
    const isValid = confidence >= 40; // Almeno 40% delle parole chiave devono essere presenti

    return { isValid, confidence, missingKeywords };
  };

  const verificationIssues = projectContext ? validateMarketingPlan(projectContext) : [];

  const handleExportPDF = () => {
    try {
      exportToPDF(marketingPlan, autoGeneratedData, verificationIssues);
      toast({ title: 'PDF esportato', description: 'Il Piano Marketing è stato esportato con successo.' });
    } catch (error) {
      toast({ title: 'Errore', description: 'Impossibile esportare il PDF.', variant: 'destructive' });
    }
  };

  const handleExportDocx = async () => {
    try {
      await exportMarketingPlanToDocx(marketingPlan, autoGeneratedData, generatedContent, verificationIssues);
      toast({ title: 'Word esportato', description: 'Il Piano Marketing è stato esportato in formato .docx.' });
    } catch (error) {
      console.error('Error exporting DOCX:', error);
      toast({ title: 'Errore', description: 'Impossibile esportare il file Word.', variant: 'destructive' });
    }
  };

  const handleGenerateAISuggestion = async (sectionId: string) => {
    setGeneratingAI(sectionId);
    try {
      const { data, error } = await supabase.functions.invoke('generate-marketing-suggestions', {
        body: { 
          sectionId,
          projectData: {
            stepProgress,
            autoGeneratedData
          }
        }
      });

      if (error) throw error;

      if (data?.error) {
        if (data.error.includes('Limite richieste')) {
          toast({
            title: 'Limite richieste superato',
            description: 'Riprova tra qualche minuto.',
            variant: 'destructive'
          });
        } else if (data.error.includes('Crediti esauriti')) {
          toast({
            title: 'Crediti esauriti',
            description: 'Aggiungi crediti al workspace per continuare.',
            variant: 'destructive'
          });
        } else {
          throw new Error(data.error);
        }
        return;
      }

      if (data?.suggestion) {
        // Validate the generated content
        const validation = validateContent(data.suggestion, projectType);
        setValidationResults(prev => ({ ...prev, [sectionId]: validation }));
        
        setEditedContent(prev => ({ ...prev, [sectionId]: data.suggestion }));
        
        if (validation.isValid) {
          toast({
            title: 'Suggerimento generato e validato',
            description: `Contenuto coerente con ${projectType} (${validation.confidence}% match).`
          });
        } else {
          toast({
            title: 'Suggerimento generato con avviso',
            description: `Il contenuto potrebbe non essere completamente coerente con ${projectType}. Considera di rigenerarlo.`,
            variant: 'destructive'
          });
        }
      }
    } catch (error) {
      console.error('Error generating AI suggestion:', error);
      toast({
        title: 'Errore',
        description: 'Impossibile generare il suggerimento AI.',
        variant: 'destructive'
      });
    } finally {
      setGeneratingAI(null);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-muted-foreground">Caricamento piano marketing...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with auto-generated insights */}
      <Card className="bg-gradient-subtle border-border/50">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex-1">
            <CardTitle className="text-2xl">Piano Marketing</CardTitle>
            <CardDescription>
              Strategia commerciale integrata con i dati del progetto
            </CardDescription>
            <div className="mt-4 max-w-xs">
              <Label htmlFor="project-type" className="text-sm font-medium">
                Tipo di Progetto
              </Label>
              <Select value={projectType} onValueChange={setProjectType}>
                <SelectTrigger id="project-type" className="mt-1.5">
                  <SelectValue placeholder="Seleziona tipo progetto" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="generale">Generale - Energia</SelectItem>
                  <SelectItem value="solare">Solare - Fotovoltaico</SelectItem>
                  <SelectItem value="eolico">Eolico - On/Off-shore</SelectItem>
                  <SelectItem value="efficienza_energetica">Efficienza Energetica</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
              <Button onClick={handleGenerateAll} variant="outline" disabled={generatingAll}>
                {generatingAll ? <RefreshCw className="h-4 w-4 mr-2 animate-spin" /> : <Wand2 className="h-4 w-4 mr-2" />}
                {generatingAll ? 'Generazione...' : 'Genera / Rigenera Tutto'}
              </Button>
              <Button onClick={handleExportDocx} variant="outline">
                <FileText className="h-4 w-4 mr-2" />
                Word
              </Button>
              <Button onClick={handleExportPDF} variant="outline">
                <Download className="h-4 w-4 mr-2" />
                PDF
              </Button>
              <Button onClick={handleSave} disabled={!hasUnsavedChanges || saving}>
                <Save className="h-4 w-4 mr-2" />
                {saving ? 'Salvataggio...' : 'Salva'}
              </Button>
            </div>
        </div>
      </CardHeader>
        {autoGeneratedData && (
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="h-5 w-5 text-primary" />
                  <span className="text-sm font-medium">Avanzamento</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingCompletionRate}%</p>
                <p className="text-xs text-muted-foreground">Attività marketing</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-5 w-5 text-green-500" />
                  <span className="text-sm font-medium">Budget Stimato</span>
                </div>
                <p className="text-lg font-bold">
                  €{autoGeneratedData.marketingCostsMin.toLocaleString('it-IT')} - €{autoGeneratedData.marketingCostsMax.toLocaleString('it-IT')}
                </p>
                <p className="text-xs text-muted-foreground">Investimento marketing</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="h-5 w-5 text-purple-500" />
                  <span className="text-sm font-medium">Timeline</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingDays}</p>
                <p className="text-xs text-muted-foreground">giorni stimati</p>
              </div>
              <div className="bg-background/50 rounded-lg p-4 border border-border/50">
                <div className="flex items-center gap-2 mb-2">
                  <Target className="h-5 w-5 text-orange-500" />
                  <span className="text-sm font-medium">Attività</span>
                </div>
                <p className="text-2xl font-bold">{autoGeneratedData.marketingSteps}</p>
                <p className="text-xs text-muted-foreground">step marketing</p>
              </div>
            </div>

            {/* Recommended Channels */}
            {autoGeneratedData.recommendedChannels && (
              <div className="mt-6">
                <h4 className="text-sm font-semibold mb-3">Canali Raccomandati</h4>
                <div className="grid grid-cols-1 md:grid-cols-5 gap-2">
                  {autoGeneratedData.recommendedChannels.map((channel: any, idx: number) => (
                    <div key={idx} className="bg-background/50 rounded-lg p-3 border border-border/50">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-medium">{channel.name}</span>
                        <Badge variant={channel.priority === 'high' ? 'default' : 'secondary'} className="text-xs">
                          {channel.priority}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{channel.budget}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        )}
      </Card>

      {/* Verification Panel */}
      <MarketingPlanVerification
        issues={verificationIssues}
        onNavigateToSection={(sectionId) => setActiveSection(sectionId)}
      />

      {/* Sections Tabs */}
      <Card>
        <Tabs value={activeSection} onValueChange={setActiveSection}>
          <CardHeader className="pb-3">
            <TabsList className="grid w-full grid-cols-3 lg:grid-cols-6">
              {sections.map((section) => (
                <TabsTrigger key={section.id} value={section.id} className="gap-2">
                  <section.icon className="h-4 w-4" />
                  <span className="hidden sm:inline">{section.label}</span>
                </TabsTrigger>
              ))}
            </TabsList>
          </CardHeader>

          {sections.map((section) => (
            <TabsContent key={section.id} value={section.id}>
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        <section.icon className="h-5 w-5" />
                        {section.label}
                      </CardTitle>
                      <CardDescription>{section.description}</CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      {(() => {
                        const status = getSectionStatus(section.id);
                        if (status === 'saved') return <Badge variant="default">Salvato</Badge>;
                        if (status === 'edited') return <Badge variant="secondary">Non salvato</Badge>;
                        if (status === 'auto') return <Badge variant="outline" className="border-primary text-primary">Auto-generato</Badge>;
                        return <Badge variant="outline" className="text-muted-foreground">Vuoto</Badge>;
                      })()}
                      {validationResults[section.id] && (
                        <Badge 
                          variant={validationResults[section.id].isValid ? "default" : "destructive"}
                          className="gap-1"
                        >
                          {validationResults[section.id].isValid ? '✓' : '⚠'} 
                          {validationResults[section.id].confidence}% match
                        </Badge>
                      )}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleGenerateSection(section.id)}
                        disabled={generatingAll}
                        title="Rigenera questa sezione dai dati del progetto"
                      >
                        {generatingAll ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
                        <span className="ml-1 hidden sm:inline">Rigenera</span>
                      </Button>
                      <Button
                        onClick={() => handleGenerateAISuggestion(section.id)}
                        disabled={generatingAI === section.id}
                        variant="outline"
                        size="sm"
                      >
                        <Sparkles className="h-4 w-4 mr-2" />
                        {generatingAI === section.id ? 'Generazione...' : 'AI'}
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea
                    value={getContent(section.id)}
                    onChange={(e) => {
                      const newContent = e.target.value;
                      setEditedContent(prev => ({ ...prev, [section.id]: newContent }));
                      // Validate manually edited content
                      if (newContent.trim().length > 50) {
                        const validation = validateContent(newContent, projectType);
                        setValidationResults(prev => ({ ...prev, [section.id]: validation }));
                      }
                    }}
                    placeholder={section.placeholder}
                    className="min-h-[400px] font-mono text-sm"
                   />
                  {getSectionStatus(section.id) === 'auto' && (
                    <div className="mt-3 p-3 bg-muted/50 rounded-lg border border-border">
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <Wand2 className="h-3 w-3" />
                        Contenuto generato automaticamente dai dati del progetto. Modificalo liberamente, poi premi "Salva" per renderlo permanente.
                      </p>
                    </div>
                  )}
                  {validationResults[section.id] && !validationResults[section.id].isValid && validationResults[section.id].missingKeywords.length > 0 && (
                    <div className="mt-3 p-3 bg-destructive/10 border border-destructive/20 rounded-md">
                      <p className="text-sm font-medium text-destructive mb-1">
                        ⚠ Il contenuto potrebbe non essere completamente coerente con il tipo di progetto "{projectType}"
                      </p>
                      <p className="text-xs text-muted-foreground">
                        Parole chiave mancanti: {validationResults[section.id].missingKeywords.slice(0, 4).join(', ')}
                        {validationResults[section.id].missingKeywords.length > 4 && '...'}
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
          ))}
        </Tabs>
      </Card>
    </div>
  );
};
